## My Machine Learning

**Machine learning** is a part of AI where computers learn from data and improve without being clearly programmed.
It finds patterns in data and uses them to make predictions or decisions.

**Requirements for machine learning data :**

1. No missing values : the model cannot handle NaN unless specially designed for it.

2. Numeric format: All features must be numeric

3. Stored in DataFrame or NumPy array: Features should be stored in a pandas DataFrame or NumPy array.

## 1. Types of machine learning

**Machine learning** has three main types: 
1. supervised learning 
2. unsupervised learning
3. reinforcement learning.

**Supervised learning** uses labeled data with features and a target variable, correct answer --> (label)

**unsupervised learning** uses only features to find patterns in the data.

**Reinforcement learning** is a type of machine learning where an agent learns by interacting with an environment and receives rewards or penalties to learn the best actions over time.

---

## 2. Independent variable and a dependent variable

In machine learning, we usually say features (independent variables) and label/target (dependent variable). 

**An independent variable** is the input feature that we choose or control.

**A dependent variable is** the target variable that depends on the independent variable.


---

## 3. The two main tasks of Supervised learning

1. **Classification** predicts a class or category (for example, yes/no or class A/B).

2. **Regression** predicts a continuous numerical value (for example, price or temperature).

----

## 4. Preprocessing

You fit preprocessing steps on the training set, and you apply the same fitted steps to the test set — even if the test set has missing values.


#### Step 1: Split first (always)
Split the data into:
- **Training set**
- **Test set**

At this point:
- Both sets may contain **missing values**
- Both sets may need **scaling**

This is normal.



#### Step 2: Fit preprocessing on the training set only

**Handling missing values**
- Compute the mean / median / most frequent value  
- **Use only the training set**
- This creates a fixed rule

**Scaling**
- Compute min & max or mean & standard deviation  
- **Use only the training set**
- This creates another fixed rule



#### Step 3: Apply the same rules to both sets

Use the rules learned from the training set to:
- Fill missing values in the **training set**
- Fill missing values in the **test set**
- Scale the **training set**
- Scale the **test set**

Even if:
- The test set has missing values → **use training-set statistics**
- The test set has a different scale → **use the training-set scaler**



#### Key rule (memorize)
**Fit preprocessing on training data. Apply it to both training and test data. Never fit on the test set.**

**Missing values are imputed by fitting the imputer on the training set only, and then applying the same imputation values to both the training and test sets.**

----

## 5. What is data leakage?

Data leakage happens when information from the test set is used during training or preprocessing.

**How leakage happens (very common)**

❌ Scaling before train/test split

❌ Imputing missing values using all data

❌ Using test data to choose parameters

**Why leakage is bad**

The test set is no longer “unseen”

Evaluation becomes unrealistic

Model will fail on real new data

----

## 6. What is scaling?

**Scaling is the process of changing feature values to a similar range so that one feature does not dominate others.**

#### Why scaling is needed
Scaling is required because some algorithms use **distance or magnitude**, such as:
- KNN
- SVM
- Linear / Ridge / Lasso Regression

If features have very different ranges, the feature with larger values dominates the model.

**Example:**
- Age: 0–100  
- Salary: 1,000–100,000  
Without scaling, salary dominates the model.



#### Common scaling methods
- **Min-Max Scaling**: scales values to a range between 0 and 1  
- **Standardization**: scales data to mean = 0 and standard deviation = 1



#### Correct scaling procedure (very important)

1. **Fit the scaler on the training set only**
   - Learn min/max or mean/standard deviation from training data

2. **Apply the same scaler to both sets**
   - Transform the training set
   - Transform the test set

Even if:
- The test set has larger or smaller values
- Scaled values go outside the 0–1 range  
→ This is correct and expected



#### Key exam rules (memorize)
- Scaling makes features comparable so models work correctly
- Fit the scaler on training data only
- Apply the same scaler to the test data
- Never compute scaling parameters from the test set


----

## 7. Pipeline

In machine learning, a pipeline is both a concept describing the workflow of steps and a scikit-learn tool that combines preprocessing and modeling into one object.

**1. Pipeline as a concept**

A pipeline is the ordered sequence of steps in machine learning: preprocessing → training → prediction → evaluation.

**2. Pipeline as a tool in scikit-learn**

There is a class called Pipeline in the scikit-learn library.

Pipeline is a tool that lets you chain preprocessing steps and a model into one single object.

### 7.1 Simple Machine Learning Pipeline (Classification & Regression)


1. **Prepare labeled data**  
   1.1 Define features (X) and target (y), convert data to numeric format,  

   1.2 then split the data into training and test sets.

   1.3 Preprocessing (fit on training data only): 
      - Handle missing values (imputation)
      - Convert text to numbers (encoding)
      - Scale / normalize features
      - Feature transformations

   Missing values and scaling are fitted on the **training set only** and applied to the test set.


2. **Choose an algorithm**  
   Select a model based on the task (classification or regression) and the data characteristics.

3. **Train the model**  
   Fit the model using the training set so it can learn patterns between X and y.


4. **Make predictions**  
   Use the trained model to predict classes (classification) or numbers (regression).

5. **Evaluate performance**  
   Measure performance using appropriate metrics  
   - Classification: accuracy, precision, recall, F1-score  
   - Regression: R², MSE, MAE  

**Note:**  
The steps are the same for classification and regression; only the algorithms and evaluation metrics differ.

---

## 8. Classification algorithms



Classification uses algorithms to predict a categorical target variable, such as:

**1. Decision Tree**
Classifies data by making a sequence of rule-based decisions on features.


**2. k-Nearest Neighbors (KNN)**
Classifies a data point based on the most common class among its K nearest neighbors.

**3. Logistic Regression**
A linear model that predicts class probabilities and assigns a class based on them.

**4. Support Vector Machine (SVM)**
Finds the decision boundary that best separates classes with the largest margin.

**5. Naive Bayes**
A probabilistic classifier based on Bayes’ theorem and the assumption of feature independence.

#### **8.1 Decision Tree**


A Decision Tree is a model that makes decisions using if–then rules.
It splits data step by step until it reaches a final decision.

Used when you want clear rules and easy explanation.
Good for small datasets and decision logic.

In [1]:
# 1. Prepare labeled data
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

X = [[1], [2], [3], [4], [5]]   # features
y = [0, 0, 0, 1, 1]            # labels

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 2. Choose an algorithm
model = DecisionTreeClassifier()

# 3. Train the model
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)


# 5. Evaluate performance
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predictions)) ## or model.score(X_test, y_test)

# Predict new data
print(model.predict([[3]]))

1.0
[0]

#### **8.2 k-Nearest Neighbors (KNN)**

KNN is a model that looks at the closest data points to make a decision.
It does not learn rules; it compares distances.


Used when similar data points have the same class.
Good for simple problems, slow on large data.

In [2]:
# 1. Prepare labeled data
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = [[1], [2], [3], [4], [5]]   # features
y = [0, 0, 0, 1, 1]            # labels

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 2. Choose an algorithm
model = KNeighborsClassifier(n_neighbors=3)

# 3. Train the model
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)

# 5. Evaluate performance
print(accuracy_score(y_test, predictions))

# Predict new data
print(model.predict([[3]]))
model.score(X_test, y_test)

1.0
[1]

1.0

#### **8.3 Logistic Regression**

Logistic Regression uses a regression formula (linear equation).

Logistic Regression is a model that uses a math formula to calculate class probability. 
It outputs values between 0 and 1 and then chooses a class.

Used when you want probabilities and simple boundaries.
Works well when data is roughly linear.


Logistic Regression: A Simple Explanation

In this video, we learned about logistic regression, a method used in machine learning to predict outcomes that can be categorized into two groups, like "yes" or "no," "pass" or "fail." Unlike regular regression, which predicts continuous values (like height or weight), logistic regression focuses on predicting a binary outcome. It does this by taking input features (like hours studied) and applying a special function that squashes the output into a range between 0 and 1, which can be interpreted as a probability.

Imagine you're trying to decide if a student will pass an exam based on how many hours they studied. If they studied for more than a certain number of hours, say three, the model predicts they have a higher chance of passing (greater than 50% probability). This way, logistic regression helps us classify data points into two categories based on their features, making it a powerful tool for binary classification tasks.

In [3]:
# 1. Prepare labeled data
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = [[1], [2], [3], [4], [5]]   # features
y = [0, 0, 0, 1, 1]            # labels

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 2. Choose an algorithm
model = LogisticRegression()

# 3. Train the model
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)

# 5. Evaluate performance
print(accuracy_score(y_test, predictions))

# Predict new data
print(model.predict([[3]]))

1.0
[0]

#### **8.4 Support Vector Machine (SVM)**

SVM is a model that finds the best boundary between classes.
It tries to separate classes with the largest possible margin.

Used when classes are hard to separate.
Works well in high-dimensional data, but slow on big datasets.

In [26]:
# 1. Prepare labeled data
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = [[1], [2], [3], [4], [5]]   # features
y = [0, 0, 0, 1, 1]            # labels

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 2. Choose an algorithm
model = SVC(kernel="linear",C=0.01)

# 3. Train the model
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)

# 5. Evaluate performance
print(accuracy_score(y_test, predictions))

# Predict new data
print(model.predict([[3]]))

1.0
[0]

#### **8.5 Naive Bayes**

Naive Bayes is a probability-based model using Bayes’ theorem.
It assumes features are independent from each other.

Used for text, spam, and fast classification.
Works well with many features and small data.

In [5]:
# 1. Prepare labeled data
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = [[1], [2], [3], [4], [5]]   # features
y = [0, 0, 0, 1, 1]            # labels

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 2. Choose an algorithm
model = GaussianNB()

# 3. Train the model
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)

# 5. Evaluate performance
print(accuracy_score(y_test, predictions))

# Predict new data
print(model.predict([[3]]))

1.0
[0]

#### **8.6 Gradient Boosting Classification**

In [6]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = [[1], [2], [3], [4], [5]]
y = [0, 0, 0, 1, 1]

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 2. Choose an algorithm
model = GradientBoostingClassifier()

# 3. Train the model
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)

# 5. Evaluate performance
print(accuracy_score(y_test, predictions))

# Predict new data
print(model.predict([[3]]))

1.0
[0]

---

## 9. Regression algorithms

Regression uses algorithms to predict a continuous target variable, such as:

- **Linear Regression**  
  Predicts numbers by fitting a straight line that minimizes error.

- **Decision Tree Regression**  
  Predicts numbers by splitting data into rules and averaging values in each leaf.

- **k-Nearest Neighbors (KNN) Regression**  
  Predicts numbers by averaging the values of the nearest data points.

- **Support Vector Regression (SVR)**  
  Predicts numbers by finding a best-fit boundary within a margin of error.

- **Random Forest Regression**  
  Predicts numbers by averaging results from many decision trees.

- **Ridge Regression**  
  Predicts like Linear Regression but penalizes large weights to reduce overfitting.

- **Lasso Regression**  
  Predicts like Linear Regression but removes less important features.

#### **9.1 Linear Regression**

What it does
Predicts a number using a straight line.

How it works
It finds the best line that minimizes prediction error.

When to use it
When the relationship is simple and roughly linear.

.coef_

The weights (coefficients) for each feature
It shows how much each feature influences the prediction.

.intercept_

The bias term (y-axis intercept)
It is the predicted value when all features are zero.

A linear model always has this form:
y = coef * x + intercept

In [ ]:
# 1. Linear Regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X = [[1], [2], [3], [4], [5]]
y = [2, 4, 6, 8, 10]

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 2. Choose an algorithm
model = LinearRegression()

# 3. Train the model
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)

# 5. Evaluate performance
print(mean_squared_error(y_test, predictions)) ## To understand prediction error size

# Predict new data
print(model.predict([[6]]))

# Inspect learned parameters
print("Coefficient (slope):", model.coef_) # → For every +1 increase in x, y increases by 2     coef = the effect of x on y
print("Intercept:", model.intercept_) # → The intercept is the predicted value of y when x = 0.

## Example :
# intercept = 5 --> x = 0 → y = 5 ,, x = 1 → y = 7 ,, x = 2 → y = 9

7.888609052210118e-31
[12.]
Coefficient (slope): [2.]
Intercept: 8.881784197001252e-16

#### **9.2 Decision Tree Regression**

What it does
Predicts a number using decision rules.

How it works
It splits data into branches and averages values in each leaf.

When to use it
When relationships are non-linear and need interpretation.

In [137]:
# 2. Decision Tree Regression
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X = [[1], [2], [3], [4], [5]]
y = [2, 4, 6, 8, 10]

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 2. Choose an algorithm
model = DecisionTreeRegressor(max_depth=2)

# 3. Train the model
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)

# 5. Evaluate performance
print(mean_squared_error(y_test, predictions)) ##

# Predict new data
print(model.predict([[6]]))

9.0
[10.]

#### **9.3 KNN Regression**

What it does
Predicts a number based on nearby data points.

How it works
It averages the target values of the closest neighbors.

When to use it
When similar inputs give similar outputs and data is small.

In [9]:
# 3. KNN Regression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X = [[1], [2], [3], [4], [5]]
y = [2, 4, 6, 8, 10]

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 2. Choose an algorithm
model = KNeighborsRegressor(n_neighbors=3)

# 3. Train the model
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)

# 5. Evaluate performance
print(mean_squared_error(y_test, predictions))

# Predict new data
print(model.predict([[6]]))

1.777777777777777
[8.]

#### **9.4 Support Vector Regression (SVR)**

What it does
Predicts numbers while allowing small errors.

How it works
It fits a function inside a margin of tolerance.

When to use it
When data is complex but not very large.

In [10]:
# 4. Support Vector Regression (SVR)
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X = [[1], [2], [3], [4], [5]]
y = [2, 4, 6, 8, 10]

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 2. Choose an algorithm
model = SVR(kernel="linear")

# 3. Train the model    
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)

# 5. Evaluate performance
print(mean_squared_error(y_test, predictions))

# Predict new data
print(model.predict([[6]]))

0.002500000000000071
[11.85]

#### **9.5 Random Forest Regression**

What it does
Predicts numbers using many decision trees.

How it works
It averages predictions from multiple trees.

When to use it
When accuracy matters more than simplicity.

In [11]:
# 5. Random Forest Regression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X = [[1], [2], [3], [4], [5]]
y = [2, 4, 6, 8, 10]

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 2. Choose an algorithm
model = RandomForestRegressor(n_estimators=10)

# 3. Train the model
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)

# 5. Evaluate performance
print(mean_squared_error(y_test, predictions))

# Predict new data
print(model.predict([[6]]))

1.0
[9.8]

#### **9.6 Ridge Regression**

What it does
Predicts numbers like Linear Regression with control.

How it works
It reduces large weights using a penalty.

When to use it
When features are many and correlated.

Ridge Regression is a technique used to improve the accuracy of a linear model by adding a penalty for large weights. Imagine you're trying to balance a seesaw. If one side is too heavy (like having large weights), it can tip over and not work well. Ridge Regression helps keep the weights balanced by gently pushing them down towards zero, which prevents the model from becoming too complex and overfitting the data. This way, the model can generalize better to new data, just like a well-balanced seesaw can accommodate different weights without tipping over.

In [19]:
# 6. Ridge Regression
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X = [[1], [2], [3], [4], [5]]
y = [2, 4, 6, 8, 10]

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 2. Choose an algorithm
model = Ridge(alpha=1.0)

# 3. Train the model
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)

# 5. Evaluate performance
print(mean_squared_error(y_test, predictions))

# Predict new data
print(model.predict([[6]]))

0.06574621959237342
[11.33333333]

    Ridge Regression uses L2 regularization, which adds a penalty equal to the square of the coefficients' values. This means it shrinks the weights but does not eliminate any features.
    Lasso Regression uses L1 regularization, which adds a penalty equal to the absolute value of the coefficients. This can shrink some weights to exactly zero, effectively removing those features from the model.

**L1 regularization adds a penalty based on the absolute value of coefficients and can set some coefficients exactly to zero (feature selection), while L2 regularization adds a penalty based on the squared value of coefficients and shrinks them without removing features.**

#### **9.7 Lasso Regression**

What it does
Predicts numbers and removes weak features.

How it works
It forces some feature weights to zero.

When to use it
When feature selection is important.

Lasso regression is a technique used in machine learning to improve the accuracy of predictions by adding a special penalty to the model. This penalty encourages the model to keep only the most important features while ignoring the less significant ones. Imagine you are packing for a trip; you want to take only the essentials and leave behind anything that isn't necessary. Lasso regression does something similar by forcing some of the feature weights to be exactly zero, which means those features won't be used in the final model.

Here's how it works: Lasso uses a method called L1 regularization, which adds a penalty based on the absolute values of the feature weights. This means that as you increase the penalty (controlled by a parameter called alpha), the model will shrink some weights down to zero, effectively selecting a simpler model with fewer features. For example, if you have a dataset with many features, lasso regression can help you identify the few that truly matter, making your model easier to interpret and often more effective.

In [21]:
# 7. Lasso Regression
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X = [[1], [2], [3], [4], [5]]
y = [2, 4, 6, 8, 10]

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 2. Choose an algorithm
model = Lasso(alpha=0.1)

# 3. Train the model
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)

# 5. Evaluate performance
print(mean_squared_error(y_test, predictions))

# Predict new data
print(model.predict([[6]]))

0.039999999999999716
[11.72]

#### **9.8 Gradient Boosting Regression**

In [14]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X = [[1], [2], [3], [4], [5]]
y = [2, 4, 6, 8, 10]

# 1.2 Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 2. Choose an algorithm
model = GradientBoostingRegressor()

# 3. Train the model
model.fit(X_train, y_train)

# 4. Make predictions (on test data)
predictions = model.predict(X_test)

# 5. Evaluate performance
print(mean_squared_error(y_test, predictions))

# Predict new data
print(model.predict([[6]]))

4.000053122974154
[9.99988047]

---

## 10. Overfitting and underfitting

| Aspect | Overfitting | Underfitting |
|------|------------|--------------|
| Definition | Model is too complex and learns noise | Model is too simple to learn the pattern |
| Typical causes | Too many parameters, high model flexibility, no regularization | Model too simple, too much regularization, wrong model choice |
| Model examples | Deep decision tree<br>Neural network with too many parameters<br>KNN with K = 1 | Linear regression on non-linear data<br>Decision tree with very small depth<br>KNN with very large K |
| Training performance | Very good | Poor |
| Test / new data performance | Poor | Poor |
| Main problem | Memorization instead of generalization | Cannot capture the data structure |

----

## 11. Generalization

**Generalization is the ability of a model to perform well on new, unseen data.**

This is the main goal of machine learning.
Not high training accuracy. Not memorization.

Overfitting means the model is too complex and memorizes the training data, which causes poor performance on unseen data.

Generalization is the ability of a model to perform well on unseen, new data.
**If a model is overfitting**, it fails to generalize and therefore cannot perform well on unseen data.

**Overfitting is the failure of generalization caused by excessive model complexity.**

#### 11.1 How regularization improves generalization ?

Regularization improves generalization by **limiting model complexity.**

**How it works:**
It adds a penalty to large weights.
This forces the model to learn simpler patterns.

**Why this helps:**
Simple models overfit less.
They perform better on new, unseen da

---

## 12. Evaluation

**Classification models** are evaluated using accuracy and class-based metrics (precision, recall, F1).

**Regression models** are evaluated using error-based metrics (MSE, RMSE, MAE) and variance-based metrics (R²).

**A single metric is never enough to judge model quality.**

**Classification and regression use different metrics,but they come from the same module: *sklearn.metrics.***

#### 12.1 Classification evaluation

| Metric | What it measures | When to use | Typical example | Main risk |
|------|-----------------|------------|-----------------|-----------|
| Accuracy | Overall correctness of predictions | Balanced classes and equal cost of FP and FN | Simple classification tasks | Misleading with imbalanced data |
| Precision | Correctness of positive predictions | When false positives are expensive | Spam detection, fraud alerts | Low recall (misses positives) |
| Recall | Ability to find all positive cases | When false negatives are expensive | Disease detection, safety systems | Many false positives |
| F1-score | Balance between precision and recall | Imbalanced classes and need one score | Text classification, ML benchmarks | Ignores true negatives |
| Confusion matrix | Breakdown of all prediction outcomes | Always, for model diagnosis | Error analysis for any classifier | No single summary number |

In [15]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

accuracy_score(y_test, y_pred)
precision_score(y_test, y_pred)
recall_score(y_test, y_pred)
f1_score(y_test, y_pred)
confusion_matrix(y_test, y_pred)

#### 12.2 Regression evaluation

| Metric | Meaning                 | Notes                   |
| ------ | ----------------------- | ----------------------- |
| MSE    | Mean Squared Error      | Penalizes large errors  |
| RMSE   | Root Mean Squared Error | Same unit as target     |
| MAE    | Mean Absolute Error     | More robust to outliers |
| R²     | Explained variance      | Can be misleading alone |

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test, predictions)
rmse = mean_squared_error(y_test, predictions, squared=False)
mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

---

## 13. Explain Concepts

#### Cross-validation

**Cross-validation is a method that evaluates a model by training and testing it on multiple different data splits to obtain a more reliable estimate of its performance.**

---

#### Principal Component Analysis (PCA)

**Principal Component Analysis is an unsupervised technique that reduces the number of features by transforming them into new variables that keep most of the data’s variance.**

---

#### Clustering in machine learning

**Clustering is an unsupervised learning method that groups similar data points together based on their features without using labels.**

---

#### Baseline in machine learning

**A baseline model is a simple reference model used to compare whether a more complex machine learning model actually performs better.**

---

#### Decision boundary in machine learning

**A decision boundary is the line or surface that separates different classes predicted by a classification model.**

---

#### least squares linear regression or ordinary least-squares.

**Ordinary Least Squares (OLS) is a linear regression method that finds the line that minimizes the sum of the squared differences between the observed values and the predicted values.**

---

#### OLS vs KNN (core difference)

**Ordinary Least Squares (OLS) is a parametric regression model that fits one global linear equation to the entire dataset by minimizing squared errors.**

---

#### regularization

**Regularization is a technique used to reduce overfitting by adding a penalty to the model that discourages overly large coefficients and overly complex models.**

----

#### Min-Max Scaling

**Min-Max Scaling is a feature scaling technique that transforms values so they lie within a fixed range, usually between 0 and 1.**

#### L1 regularization & L2 regularization

**L1 regularization adds a penalty based on the absolute value of coefficients and can set some coefficients exactly to zero (feature selection), while L2 regularization adds a penalty based on the squared value of coefficients and shrinks them without removing features.**

Sure! Let's talk about linear classification, which is a method used to categorize data into two groups, often called classes. Imagine you have a basket of fruits, and you want to separate apples from oranges. Linear classification helps you draw a straight line (or boundary) that divides the apples from the oranges based on their features, like size and color. 

In this method, we use a mathematical function that takes the features of each fruit (like size and color) and gives us a prediction: is it an apple (+1) or an orange (-1)? If the function's output is greater than zero, we classify it as an apple; if it's less than zero, we classify it as an orange. This way, we can easily categorize new fruits based on their features!

--------

## My First Model

In [1]:
import pandas as pd

data = pd.read_csv(r"C:\Users\adels\Desktop\My ML\storedata_clean.csv",sep=';')

df = pd.DataFrame(data)
df

,Town,Country,Store ID,Manager name,Staff,Floor Space,Window,Car park,Demographic score,Location,40min population,30 min population,20 min population,10 min population,Store age,Clearance space,Competition number,Competition score,Profit,Performance
0,Swinton (Greater Manchester),UK,1437,Roger,9,18526,121,Yes,10,Retail Park,1288374,1138224,1006986,1002340,3,238,16,16,3410865,Good
1,Stamford,UK,1544,Ella,8,18569,121,Yes,11,Shopping Centre,1086225,1015321,1012182,1008436,4,384,15,19,4034051,Excellent
2,Skipton,UK,2039,Valentina,2,12288,105,No,12,Retail Park,1595638,1281661,1104490,1011395,11,219,13,18,2297810,Poor
3,Stratton,UK,2055,Antonia,7,17092,117,No,14,High Street,1179395,1022959,1009496,1002169,5,261,15,12,2398990,Poor
4,Shepperton,UK,2141,Gabriel,7,11307,103,No,18,Retail Park,1398558,1085170,1003137,1002513,7,200,19,13,2288235,Poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,South Benfleet,UK,96853,Vitória,7,14120,110,Yes,13,Retail Park,1665074,1240813,1141898,1041041,6,202,18,14,2581954,Reasonable
132,Sandy,UK,96858,Matías,6,11205,103,No,15,Shopping Centre,1657769,1424404,1378708,1160929,5,203,13,18,2589339,Reasonable
133,Sheerness,UK,98062,Gustavo,7,16190,115,No,19,Shopping Centre,1407456,1359511,1200486,1063718,7,341,18,18,2583755,Reasonable
134,Salford,UK,98923,Rafael,6,15516,113,No,17,High Street,1451087,1245725,1127276,1045154,11,261,14,10,950924,Poor
135,Stapleford,UK,99854,Lea,9,14468,111,Yes,18,High Street,1706344,1307752,1159859,1020940,8,276,18,13,3485295,Good

In [2]:
for i in df.index:
    value = df.loc[i,"Car park"]
    if value == "Y":
        value = "Yes"
    elif value == "N":
        value = "No"
    df.loc[i,"Car park"] = value

In [3]:
for i in df.index :
    value = df.loc[i,"Staff"]
    if value < 0:
        value = abs(value)
    elif value >= 100:
        value = value / 100
    df.loc[i,'Staff'] = value

In [4]:
drop_cols = [
    "Profit",          # target
    "Store ID",        # identifier
    "Manager name",    # personal, non-generalizable
    "Town",            # high-cardinality text
    "Performance"      # likely derived from profit → leakage
]

X = df.drop(columns=drop_cols)
y = df["Profit"]

In [5]:
X

,Country,Staff,Floor Space,Window,Car park,Demographic score,Location,40min population,30 min population,20 min population,10 min population,Store age,Clearance space,Competition number,Competition score
0,UK,9,18526,121,Yes,10,Retail Park,1288374,1138224,1006986,1002340,3,238,16,16
1,UK,8,18569,121,Yes,11,Shopping Centre,1086225,1015321,1012182,1008436,4,384,15,19
2,UK,2,12288,105,No,12,Retail Park,1595638,1281661,1104490,1011395,11,219,13,18
3,UK,7,17092,117,No,14,High Street,1179395,1022959,1009496,1002169,5,261,15,12
4,UK,7,11307,103,No,18,Retail Park,1398558,1085170,1003137,1002513,7,200,19,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,UK,7,14120,110,Yes,13,Retail Park,1665074,1240813,1141898,1041041,6,202,18,14
132,UK,6,11205,103,No,15,Shopping Centre,1657769,1424404,1378708,1160929,5,203,13,18
133,UK,7,16190,115,No,19,Shopping Centre,1407456,1359511,1200486,1063718,7,341,18,18
134,UK,6,15516,113,No,17,High Street,1451087,1245725,1127276,1045154,11,261,14,10
135,UK,9,14468,111,Yes,18,High Street,1706344,1307752,1159859,1020940,8,276,18,13

### Handling categorical column in X

In [6]:
categorical_cols = X.select_dtypes(include=["object"]).columns
numerical_cols = X.select_dtypes(exclude=["object"]).columns

In [7]:
categorical_cols

Index(['Country', 'Car park', 'Location'], dtype='object')

##### Option A - Data (1)

In [8]:
X_Data= X.copy()

In [194]:
list(set(X_Data['Location']))

['High Street', 'Shopping Centre', 'Retail Park', 'Village']

In [175]:
X_Data["Country"].replace(('France', 'UK'),(1,2),inplace=True)
X_Data["Car park"].replace(('No', 'Yes'),(0,1),inplace=True)
X_Data["Location"].replace(('High Street', 'Shopping Centre', 'Retail Park', 'Village'),(1,2,3,4),inplace=True)

C:\Users\adels\AppData\Local\Temp\ipykernel_23688\801424233.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_Data["Country"].replace(('France', 'UK'),(1,2),inplace=True)
C:\Users\adels\AppData\Local\Temp\ipykernel_23688\801424233.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_Data["Country"].replace(('France', 'UK'),(1,2),inplace=True)
C:\Users\adels\AppData\Local\Temp\ipykernel_23688\801424233.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_Data["Car park"].replace(('No', 'Yes'),(0,1),inplace=True)
C:\Users\adels\AppData\Local\Temp\ipykernel_23688\801424233.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_Data["Car park"].replace(('No', 'Yes'),(0,1),inplace=True)
C:\Users\adels\AppData\Local\Temp\ipykernel_23688\801424233.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_Data["Location"].replace(('High Street', 'Shopping Centre', 'Retail Park', 'Village'),(1,2,3,4),inplace=True)
C:\Users\adels\AppData\Local\Temp\ipykernel_23688\801424233.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_Data["Location"].replace(('High Street', 'Shopping Centre', 'Retail Park', 'Village'),(1,2,3,4),inplace=True)

In [176]:
X_Data.dtypes

Country               int64
Staff                 int64
Floor Space           int64
Window                int64
Car park              int64
Demographic score     int64
Location              int64
40min population      int64
30 min population     int64
20 min population     int64
10 min population     int64
Store age             int64
Clearance space       int64
Competition number    int64
Competition score     int64
dtype: object

--------

##### Option B — Quick & dirty

In [177]:
X_encoded = pd.get_dummies(X, drop_first=True)
X_encoded.dtypes

Staff                       int64
Floor Space                 int64
Window                      int64
Demographic score           int64
40min population            int64
30 min population           int64
20 min population           int64
10 min population           int64
Store age                   int64
Clearance space             int64
Competition number          int64
Competition score           int64
Country_UK                   bool
Car park_Yes                 bool
Location_Retail Park         bool
Location_Shopping Centre     bool
Location_Village             bool
dtype: object

----

##### Option C — Correct ML approach


Use ColumnTransformer + OneHotEncoder.

In [178]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [203]:
categorical_cols

Index(['Country', 'Car park', 'Location'], dtype='object')

In [204]:
numerical_cols

Index(['Staff', 'Floor Space', 'Window', 'Demographic score',
       '40min population', '30 min population', '20 min population',
       '10 min population', 'Store age', 'Clearance space',
       'Competition number', 'Competition score'],
      dtype='object')

In [ ]:
preprocessor = ColumnTransformer(transformers=[("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),("num", "passthrough", numerical_cols)])

X_encoded1 = preprocessor.fit_transform(X)

In [206]:
X_encoded_df = pd.DataFrame(
    X_encoded1,
    columns=preprocessor.get_feature_names_out(),
    index=X.index
)
X_encoded_df.info()
X_encoded_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   cat__Country_France            136 non-null    float64
 1   cat__Country_UK                136 non-null    float64
 2   cat__Car park_No               136 non-null    float64
 3   cat__Car park_Yes              136 non-null    float64
 4   cat__Location_High Street      136 non-null    float64
 5   cat__Location_Retail Park      136 non-null    float64
 6   cat__Location_Shopping Centre  136 non-null    float64
 7   cat__Location_Village          136 non-null    float64
 8   num__Staff                     136 non-null    float64
 9   num__Floor Space               136 non-null    float64
 10  num__Window                    136 non-null    float64
 11  num__Demographic score         136 non-null    float64
 12  num__40min population          136 non-null    float64
 13  num__30 min population         136 non-null    float64
 14  num__20 min population         136 non-null    float64
 15  num__10 min population         136 non-null    float64
 16  num__Store age                 136 non-null    float64
 17  num__Clearance space           136 non-null    float64
 18  num__Competition number        136 non-null    float64
 19  num__Competition score         136 non-null    float64
dtypes: float64(20)
memory usage: 21.4 KB

,cat__Country_France,cat__Country_UK,cat__Car park_No,cat__Car park_Yes,cat__Location_High Street,cat__Location_Retail Park,cat__Location_Shopping Centre,cat__Location_Village,num__Staff,num__Floor Space,num__Window,num__Demographic score,num__40min population,num__30 min population,num__20 min population,num__10 min population,num__Store age,num__Clearance space,num__Competition number,num__Competition score
0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,9.0,18526.0,121.0,10.0,1288374.0,1138224.0,1006986.0,1002340.0,3.0,238.0,16.0,16.0
1,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,8.0,18569.0,121.0,11.0,1086225.0,1015321.0,1012182.0,1008436.0,4.0,384.0,15.0,19.0
2,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,12288.0,105.0,12.0,1595638.0,1281661.0,1104490.0,1011395.0,11.0,219.0,13.0,18.0
3,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,7.0,17092.0,117.0,14.0,1179395.0,1022959.0,1009496.0,1002169.0,5.0,261.0,15.0,12.0
4,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,7.0,11307.0,103.0,18.0,1398558.0,1085170.0,1003137.0,1002513.0,7.0,200.0,19.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,7.0,14120.0,110.0,13.0,1665074.0,1240813.0,1141898.0,1041041.0,6.0,202.0,18.0,14.0
132,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,6.0,11205.0,103.0,15.0,1657769.0,1424404.0,1378708.0,1160929.0,5.0,203.0,13.0,18.0
133,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,7.0,16190.0,115.0,19.0,1407456.0,1359511.0,1200486.0,1063718.0,7.0,341.0,18.0,18.0
134,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,6.0,15516.0,113.0,17.0,1451087.0,1245725.0,1127276.0,1045154.0,11.0,261.0,14.0,10.0
135,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,9.0,14468.0,111.0,18.0,1706344.0,1307752.0,1159859.0,1020940.0,8.0,276.0,18.0,13.0

-----

##### Option D Ordinal Encoding (ONLY if ordered)



Use Ordinal Encoding only when the categories have a real, meaningful order that the model should use.
So in my case here is not correct!!

EX : OrdinalEncoder(
    categories=[['Poor', 'Reasonable', 'Good', 'Excellent']]
)

In [105]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder

In [100]:
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OrdinalEncoder(), categorical_cols),
        ("num", "passthrough", numerical_cols)
    ]
)

X_encoded2 = preprocessor.fit_transform(X)

In [101]:
X_encoded_df1 = pd.DataFrame(
    X_encoded2,
    columns=preprocessor.get_feature_names_out(),
    index=X.index
)
X_encoded_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cat__Country             136 non-null    float64
 1   cat__Car park            136 non-null    float64
 2   cat__Location            136 non-null    float64
 3   num__Staff               136 non-null    float64
 4   num__Floor Space         136 non-null    float64
 5   num__Window              136 non-null    float64
 6   num__Demographic score   136 non-null    float64
 7   num__40min population    136 non-null    float64
 8   num__30 min population   136 non-null    float64
 9   num__20 min population   136 non-null    float64
 10  num__10 min population   136 non-null    float64
 11  num__Store age           136 non-null    float64
 12  num__Clearance space     136 non-null    float64
 13  num__Competition number  136 non-null    float64
 14  num__Competition score   136 non-null    float64
dtypes: float64(15)
memory usage: 16.1 KB

----

##### Option E Frequency / Count Encoding 

CountEncoder replaces categories with their frequency.

In [111]:
from category_encoders import CountEncoder

encoder = CountEncoder(cols=categorical_cols)
X_encoded = encoder.fit_transform(X)
X_encoded["Location"].unique()

array([43, 52, 40,  1])

-----------

In [136]:
from category_encoders import TargetEncoder

encoder = TargetEncoder(cols=categorical_cols)
X_encoded = encoder.fit_transform(X, y)

----

##### Option F binary encoding




Binary encoding transforms categories into binary digits. This method uses fewer columns than one-hot encoding and is often used for high-cardinality features.

When to Use:

    When the dataset has many categories and one-hot encoding leads to too many features.
    When a relationship between categories and the target variable is expected.

In [114]:
from category_encoders import BinaryEncoder

encoder = BinaryEncoder(cols=categorical_cols)
X_encoded = encoder.fit_transform(X)
X_encoded

,Country_0,Country_1,Staff,Floor Space,Window,Car park_0,Car park_1,Demographic score,Location_0,Location_1,Location_2,40min population,30 min population,20 min population,10 min population,Store age,Clearance space,Competition number,Competition score
0,0,1,9,18526,121,0,1,10,0,0,1,1288374,1138224,1006986,1002340,3,238,16,16
1,0,1,8,18569,121,0,1,11,0,1,0,1086225,1015321,1012182,1008436,4,384,15,19
2,0,1,2,12288,105,1,0,12,0,0,1,1595638,1281661,1104490,1011395,11,219,13,18
3,0,1,7,17092,117,1,0,14,0,1,1,1179395,1022959,1009496,1002169,5,261,15,12
4,0,1,7,11307,103,1,0,18,0,0,1,1398558,1085170,1003137,1002513,7,200,19,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,0,1,7,14120,110,0,1,13,0,0,1,1665074,1240813,1141898,1041041,6,202,18,14
132,0,1,6,11205,103,1,0,15,0,1,0,1657769,1424404,1378708,1160929,5,203,13,18
133,0,1,7,16190,115,1,0,19,0,1,0,1407456,1359511,1200486,1063718,7,341,18,18
134,0,1,6,15516,113,1,0,17,0,1,1,1451087,1245725,1127276,1045154,11,261,14,10
135,0,1,9,14468,111,0,1,18,0,1,1,1706344,1307752,1159859,1020940,8,276,18,13

------

#### Option G LabelEncoder

1. Label Encoding

Label encoding is the simplest form of encoding. It assigns each unique category value an integer, starting from 0. While it’s straightforward, label encoding can impose an ordinal relationship between categories, which may not always be desirable.

When should we use this:

    When the categorical variable is ordinal (i.e., has a natural order).
    When there are no issues with imposing a numerical relationship between categories.

Key Notes: Label encoding is quick and efficient but may cause problems when the categories don’t have an ordinal relationship.

In [158]:
from sklearn.preprocessing import LabelEncoder

# Sample data
data = ['cat', 'dog', 'fish', 'cat', 'dog']

# Initialize the encoder
le = LabelEncoder()

# Fit and transform the data
encoded_data = le.fit_transform(data)

print(encoded_data)

[0 1 2 0 1]

______

Choosing the Right Encoder

The choice of encoder depends largely on the problem you’re working on and the nature of your dataset:

    Label Encoding is useful when there’s a natural ordinal relationship.
    One-Hot Encoding is ideal for nominal categories but can lead to high dimensionality.
    Target Encoding and Binary Encoding are better for high-cardinality features but come with the risk of overfitting.
    Frequency Encoding is a quick way to retain the distribution of the categorical data.

Each method has it’s own pros and cons, so it’s important to experiment and understand the characteristics of your data before choosing the right encoding technique.

____

One-hot encoding creates binary columns for each category, marking 1 for the presence of the category and 0 otherwise. This method prevents the model from assuming any ordinal relationship between categories.

When should we use this:

    When the categorical variable is nominal (i.e., categories do not have an intrinsic order).
    When you have a limited number of categories.


Key Notes: One-hot encoding creates additional dimensions, which can become a concern if the number of unique categories is very high (dimensionality explosion).

_____

### OneHotEncoder


What it does
Creates one column per category.

Use when

Categories have no order

Low or medium number of categories

Pros

No fake order

Works with linear models

Cons

Many columns if cardinality is high

Tool

OneHotEncoder

In [ ]:
preprocessor = ColumnTransformer(transformers=[("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),("num", "passthrough", numerical_cols)])

X_encoded1 = preprocessor.fit_transform(X_train)
X_encoded_df = pd.DataFrame(
    X_encoded1,
    columns=preprocessor.get_feature_names_out(),
    index=X_train.index
)
X_encoded_df.info()
X_encoded_df

<class 'pandas.core.frame.DataFrame'>
Index: 108 entries, 11 to 102
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   cat__Country_France            108 non-null    float64
 1   cat__Country_UK                108 non-null    float64
 2   cat__Car park_No               108 non-null    float64
 3   cat__Car park_Yes              108 non-null    float64
 4   cat__Location_High Street      108 non-null    float64
 5   cat__Location_Retail Park      108 non-null    float64
 6   cat__Location_Shopping Centre  108 non-null    float64
 7   cat__Location_Village          108 non-null    float64
 8   num__Staff                     108 non-null    float64
 9   num__Floor Space               108 non-null    float64
 10  num__Window                    108 non-null    float64
 11  num__Demographic score         108 non-null    float64
 12  num__40min population          108 non-null    float64
 13  num__30 min population         108 non-null    float64
 14  num__20 min population         108 non-null    float64
 15  num__10 min population         108 non-null    float64
 16  num__Store age                 108 non-null    float64
 17  num__Clearance space           108 non-null    float64
 18  num__Competition number        108 non-null    float64
 19  num__Competition score         108 non-null    float64
dtypes: float64(20)
memory usage: 17.7 KB

,cat__Country_France,cat__Country_UK,cat__Car park_No,cat__Car park_Yes,cat__Location_High Street,cat__Location_Retail Park,cat__Location_Shopping Centre,cat__Location_Village,num__Staff,num__Floor Space,num__Window,num__Demographic score,num__40min population,num__30 min population,num__20 min population,num__10 min population,num__Store age,num__Clearance space,num__Competition number,num__Competition score
11,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,8.0,11071.0,102.0,12.0,1514670.0,1400857.0,1319646.0,1010879.0,11.0,202.0,15.0,10.0
68,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,6.0,13709.0,109.0,11.0,1061935.0,1006165.0,1002529.0,1001991.0,8.0,291.0,14.0,11.0
129,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,9.0,10080.0,100.0,19.0,1541541.0,1474539.0,1462733.0,1384705.0,6.0,200.0,16.0,18.0
76,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,7.0,10072.0,100.0,15.0,1258330.0,1256349.0,1184882.0,1072598.0,5.0,200.0,14.0,12.0
84,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,6.0,13283.0,108.0,19.0,1605018.0,1517910.0,1090982.0,1064902.0,4.0,243.0,15.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,5.0,15876.0,114.0,14.0,1423209.0,1408262.0,1185937.0,1046917.0,7.0,315.0,12.0,11.0
106,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,7.0,11198.0,102.0,18.0,1045772.0,1002236.0,1000642.0,1000002.0,3.0,206.0,18.0,10.0
14,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,5.0,14588.0,111.0,17.0,1242546.0,1053056.0,1047783.0,1007899.0,10.0,261.0,11.0,19.0
92,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,8.0,13635.0,109.0,16.0,1549510.0,1174611.0,1063668.0,1009045.0,5.0,251.0,19.0,11.0
102,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,6.0,19223.0,123.0,18.0,1261985.0,1095548.0,1017140.0,1000639.0,9.0,266.0,19.0,14.0

In [9]:
df

,Town,Country,Store ID,Manager name,Staff,Floor Space,Window,Car park,Demographic score,Location,40min population,30 min population,20 min population,10 min population,Store age,Clearance space,Competition number,Competition score,Profit,Performance
0,Swinton (Greater Manchester),UK,1437,Roger,9,18526,121,Yes,10,Retail Park,1288374,1138224,1006986,1002340,3,238,16,16,3410865,Good
1,Stamford,UK,1544,Ella,8,18569,121,Yes,11,Shopping Centre,1086225,1015321,1012182,1008436,4,384,15,19,4034051,Excellent
2,Skipton,UK,2039,Valentina,2,12288,105,No,12,Retail Park,1595638,1281661,1104490,1011395,11,219,13,18,2297810,Poor
3,Stratton,UK,2055,Antonia,7,17092,117,No,14,High Street,1179395,1022959,1009496,1002169,5,261,15,12,2398990,Poor
4,Shepperton,UK,2141,Gabriel,7,11307,103,No,18,Retail Park,1398558,1085170,1003137,1002513,7,200,19,13,2288235,Poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,South Benfleet,UK,96853,Vitória,7,14120,110,Yes,13,Retail Park,1665074,1240813,1141898,1041041,6,202,18,14,2581954,Reasonable
132,Sandy,UK,96858,Matías,6,11205,103,No,15,Shopping Centre,1657769,1424404,1378708,1160929,5,203,13,18,2589339,Reasonable
133,Sheerness,UK,98062,Gustavo,7,16190,115,No,19,Shopping Centre,1407456,1359511,1200486,1063718,7,341,18,18,2583755,Reasonable
134,Salford,UK,98923,Rafael,6,15516,113,No,17,High Street,1451087,1245725,1127276,1045154,11,261,14,10,950924,Poor
135,Stapleford,UK,99854,Lea,9,14468,111,Yes,18,High Street,1706344,1307752,1159859,1020940,8,276,18,13,3485295,Good

In [10]:
drop_cols = [
    "Profit",          # target
    "Store ID",        # identifier
    "Manager name",    # personal, non-generalizable
    "Town",            # high-cardinality text
    "Performance"      # likely derived from profit → leakage
]

X = df.drop(columns=drop_cols)
y = df["Profit"]

In [11]:
categorical_cols = X.select_dtypes(include=["object"]).columns
numerical_cols = X.select_dtypes(exclude=["object"]).columns

In [12]:
from sklearn.preprocessing import OneHotEncoder # converts text categories into numbers (0/1)
from sklearn.compose import ColumnTransformer   # applies different preprocessing to different columns
from sklearn.pipeline import Pipeline           # chains preprocessing and model into one object

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42
)

In [16]:
preprocessor = ColumnTransformer(transformers=[("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),("num", "passthrough", numerical_cols)])
preprocessor.fit_transform(X_train)

array([[  0.,   1.,   0., ..., 238.,  16.,  16.],
       [  0.,   1.,   1., ..., 204.,  18.,  14.],
       [  0.,   1.,   0., ..., 206.,  19.,  16.],
       ...,
       [  0.,   1.,   0., ..., 261.,  11.,  19.],
       [  0.,   1.,   0., ..., 251.,  19.,  11.],
       [  0.,   1.,   0., ..., 266.,  19.,  14.]], shape=(102, 20))

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("R²:", r2)

MAE: 412825.6746701167
R²: 0.47381948379521355

In [21]:
from sklearn.ensemble import RandomForestRegressor

model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(
    n_estimators=300,
    max_depth=10,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
))
])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("R²:", r2)

MAE: 446171.63888165524
R²: 0.44596185217295004

In [20]:
from sklearn.ensemble import GradientBoostingRegressor

model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("regressor", GradientBoostingRegressor(
        n_estimators=300,
        learning_rate=0.05,
        random_state=42
    ))
])

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2:", r2_score(y_test, y_pred))

MAE: 469751.96236089594
R2: 0.3673373104414971

In [19]:
from sklearn.linear_model import Ridge

model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2:", r2_score(y_test, y_pred))

MAE: 409382.07591123297
R2: 0.4782497098421701

In [34]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error


scores = cross_val_score(
    model, X, y,
    scoring="neg_mean_absolute_error",
    cv=5
)

print("Mean MAE:", -scores.mean())
print("MAE per fold:", -scores)
print("Std MAE:", scores.std())

## again Cross V

from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    model,
    X,
    y,
    scoring="neg_mean_absolute_error",
    cv=5,
    n_jobs=-1
)

print("Mean MAE:", -scores.mean())
print("Std MAE:", scores.std())


## MAE

mae = mean_absolute_error(y_test, y_pred)
print(f"MAE : {mae}")

Mean MAE: 383673.9699931928
MAE per fold: [302389.18467532 416944.27936363 345259.30085589 443398.40466128
 410378.68040984]
Std MAE: 51903.69210290528
Mean MAE: 383673.9699931928
Std MAE: 51903.69210290528
MAE : 412825.6746701167

In [20]:
mae/df["Profit"].mean()

np.float64(0.11469047581001823)

________

In [ ]:
import pandas as pd
from sklearn.datasets import load_diabetes

data = load_diabetes()

df = pd.DataFrame(
    data.data,
    columns=data.feature_names
)

df["target"] = data.target


# or

#data = load_diabetes(as_frame=True)
#df = data.frame

In [11]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

This is called **z-score standardization**:

For each column separately (age, bmi, bp, …), scikit-learn did this:

zi= (xi−μ) / σ


Where:

xi= original value (for one person)

μ = mean of that column (all people)

σ = standard deviation of that column

This was done once, before the dataset was released.

or like thta : 

(age − mean_age) / std_age

In [15]:
X = df.drop(columns="target")
y = df["target"]

In [16]:
X.shape

(442, 10)

In [17]:
y.shape

(442,)

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42
)

In [19]:
print (X_train.shape)
print (y_train.shape)
print (X_test.shape)
print (y_test.shape)

(331, 10)
(331,)
(111, 10)
(111,)

In [22]:
df["target"].describe()

count    442.000000
mean     152.133484
std       77.093005
min       25.000000
25%       87.000000
50%      140.500000
75%      211.500000
max      346.000000
Name: target, dtype: float64

In machine learning, a
baseline is the simplest possible model you can build to solve a problem.

In [ ]:
model = LinearRegression()

Which evaluation metric will you use first — and why?

MAE → tells you the average size of your error (easy to interpret)

MSE → it penalizes large errors more, which makes it sensitive to outliers 

R² → tells you how much variance you explain, not how wrong you are